"""initial schema

Revision ID: 1ed3a9e31e3a
Revises:
Create Date: 2026-09-21 22:21:32.499532

"""

# ruff: noqa: E501
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ed3a9e31e3a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.CheckConstraint("role IN ('ADMIN', 'LELTAROZO', 'OLVASO')", name="ck_app_user_role"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "asset_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("name_normalized", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name_normalized"),
    )
    op.create_table(
        "import_batch",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("file_name", sa.Text(), nullable=True),
        sa.Column("source_system", sa.Text(), nullable=True),
        sa.Column("rows_read", sa.Integer(), nullable=True),
        sa.Column("rows_ok", sa.Integer(), nullable=True),
        sa.Column("rows_failed", sa.Integer(), nullable=True),
        sa.Column(
            "imported_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("imported_by", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inventory_period",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("state", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "state IN ('DRAFT', 'ACTIVE', 'CLOSED')", name="ck_inventory_period_state"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inventory_zone",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("site_code", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "asset",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("asset_number", sa.Text(), nullable=False),
        sa.Column("sub_number", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("name_normalized", sa.Text(), nullable=False),
        sa.Column("zone_id", sa.Integer(), nullable=True),
        sa.Column("asset_type_id", sa.Integer(), nullable=True),
        sa.Column("parent_asset_id", sa.Uuid(), nullable=True),
        sa.Column("original_asset", sa.Text(), nullable=True),
        sa.Column("tax_ref", sa.Text(), nullable=True),
        sa.Column("activated_on", sa.Date(), nullable=True),
        sa.Column("gross_value", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("accum_depreciation", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("book_value", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), server_default=sa.text("'HUF'"), nullable=False),
        sa.Column("serial_number", sa.Text(), nullable=True),
        sa.Column("quantity", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("import_batch_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["asset_type_id"],
            ["asset_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["import_batch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_asset_id"],
            ["asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["inventory_zone.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_number", "sub_number", name="uq_asset_number_sub_number"),
    )
    op.create_table(
        "room",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("zone_id", sa.Integer(), nullable=False),
        sa.Column("building", sa.Text(), nullable=True),
        sa.Column("floor", sa.Text(), nullable=True),
        sa.Column("room_number", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["inventory_zone.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "asset_code",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("zone_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("code_normalized", sa.Text(), nullable=False),
        sa.Column("code_type", sa.Text(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.CheckConstraint(
            "code_type IN ('LELTARSZAM', 'ESZKOZSZAM', 'GYARI_SZAM', 'SAJAT_CIMKE')",
            name="ck_asset_code_type",
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["inventory_zone.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("zone_id", "code_normalized", name="uq_asset_code_zone_normalized"),
    )
    op.create_table(
        "inventory_session",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("period_id", sa.Uuid(), nullable=False),
        sa.Column("zone_id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["inventory_period.id"],
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["room.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["inventory_zone.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scan",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=True),
        sa.Column("raw_code", sa.Text(), nullable=False),
        sa.Column("code_normalized", sa.Text(), nullable=False),
        sa.Column("result", sa.Text(), nullable=False),
        sa.Column("quantity_delta", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("verification", sa.Text(), server_default=sa.text("'DIRECT'"), nullable=False),
        sa.Column("room_id", sa.Uuid(), nullable=True),
        sa.Column(
            "scanned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("scanned_by", sa.Uuid(), nullable=True),
        sa.Column("compensates_scan_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "result IN ('FOUND', 'UNKNOWN_CODE', 'FOREIGN_ZONE', 'SURPLUS')", name="ck_scan_result"
        ),
        sa.CheckConstraint("verification IN ('DIRECT', 'INHERITED')", name="ck_scan_verification"),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["compensates_scan_id"],
            ["scan.id"],
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["room.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scanned_by"],
            ["app_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["inventory_session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
    op.execute("""
        CREATE FUNCTION scan_is_append_only() RETURNS trigger AS $BODY$
        BEGIN
          RAISE EXCEPTION 'a scan tabla csak bovulhet';
        END;
        $BODY$ LANGUAGE plpgsql;
    """)

    op.execute("""
        CREATE TRIGGER scan_no_update_delete
          BEFORE UPDATE OR DELETE ON scan
          FOR EACH ROW EXECUTE FUNCTION scan_is_append_only();
    """)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS scan_no_update_delete ON scan")
    op.execute("DROP FUNCTION IF EXISTS scan_is_append_only()")
    """Downgrade schema."""
    op.drop_table("scan")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scan")
    op.drop_table("inventory_session")
    op.drop_table("asset_code")
    op.drop_table("room")
    op.drop_table("asset")
    op.drop_table("inventory_zone")
    op.drop_table("inventory_period")
    op.drop_table("import_batch")
    op.drop_table("asset_type")
    op.drop_table("app_user")
    # ### end Alembic commands ###
